plugins {
    id 'java-library'
    id 'idea'
}

allprojects {
    group = mod_group_id
    version = mod_version

    repositories {
        mavenLocal()
        maven { url = "https://maven.blamejared.com" }
        maven { url = "https://api.modrinth.com/maven" }
        maven { url = "https://maven.terraformersmc.com/releases/" }
        maven { url = "https://maven.minecraftforge.net" }
        maven { url = "https://maven.neoforged.net/releases" }
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

sourceSets {
    main {
        java.setSrcDirs([])
        resources.setSrcDirs([])
    }
    test {
        java.setSrcDirs([])
        resources.setSrcDirs([])
    }
}

dependencies {
    compileOnly "it.unimi.dsi:fastutil:8.5.12"
    compileOnly "com.google.code.gson:gson:2.10.1"
    compileOnly "org.spongepowered:mixin:0.8.5"
    compileOnly "org.ow2.asm:asm-tree:9.7.1"

    compileOnly "mezz.jei:jei-${forge_minecraft_version}-forge-api:${forge_jei_version}"
    compileOnly "mezz.jei:jei-${forge_minecraft_version}-forge:${forge_jei_version}"
    compileOnly "dev.emi:emi-forge:${forge_emi_version}+${forge_minecraft_version}"

    testImplementation sourceSets.main.output
    testImplementation "org.junit.jupiter:junit-jupiter:5.9.3"
    testImplementation "it.unimi.dsi:fastutil:8.5.12"
    testImplementation "com.google.code.gson:gson:2.10.1"
    testImplementation "org.spongepowered:mixin:0.8.5"
    testImplementation "org.ow2.asm:asm-tree:9.7.1"
    testImplementation "mezz.jei:jei-${forge_minecraft_version}-forge-api:${forge_jei_version}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.9.3"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:1.9.3"
}

tasks.named('compileJava', JavaCompile).configure {
    source = files()
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
    dependsOn ':neoforge:test'
}
