# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.console=rich
# ModDevGradle
moddevgradle_version=2.0.141
# NeoForge 1.21.1 target.
neoforge_minecraft_version=1.21.1
neoforge_minecraft_version_range=[1.21.1]
neoforge_version=21.1.248
neoforge_version_range=[21.1.200,)
neoforge_loader_version_range=[1,)
neoforge_parchment_minecraft_version=1.21.1
neoforge_parchment_mappings_version=2024.11.17
neoforge_jei_version=19.43.0.394
neoforge_emi_version=1.1.24
neoforge_kubejs_version=2101.7.2-build.295
# Forge 1.20.1 target.
forge_minecraft_version=1.20.1
forge_minecraft_version_range=[1.20.1, 1.21)
forge_version=47.4.20
forge_version_range=[47,)
forge_loader_version_range=[47,)
forge_parchment_minecraft_version=1.20.1
forge_parchment_mappings_version=2023.09.03
forge_jei_version=15.48.0.180
forge_emi_version=1.1.24
## Mod Properties
mod_id=ami
mod_name=Automated Materials Index
mod_license=MIT
mod_version=1.8.6
mod_group_id=com.sanhiruzu.ami
## Recipe UI Integration
# none | emi | jei | both
dev_recipe_viewer=both
# Fabric 1.21.1 target.
fabric_minecraft_version=1.21.1
fabric_loom_version=1.7.4
fabric_loader_version=0.19.3
fabric_api_version=0.116.12+1.21.1
fabric_jei_version=19.43.0.394
fabric_emi_version=1.1.24
fabric_rei_version=16.0.799
